### ISSUE TITLE
 Styling end.html file  

### ISSUE THREAD

**Issue by Rahulkumar2002** [arnav1776/Hogwarts#20]
Hi **Arnav1776** , I would like to contribute in this project by styling end.html file and  I would love to make some documentation on how to use end.html page which could be added in your readme for ease of user's and if there anything else you want to add in end.html , I would like to know it .  Also add **HacktoberFest**  label on this issue . Thank You .

**Comment by arnav1776** [comment]
There is already someone working on end.html you can work on the documentation  part.

**Comment by arnav1776** [comment]
![IMG_20211007_154054](https://user-images.githubusercontent.com/64467851/136364951-51a207fb-08cc-423f-9c88-e6cc8a1d6861.jpg)

Don't remove that line instead add you feature between these two sections, also create a new pr for any new change that you want to add.

**Comment by Rahulkumar2002** [comment]
ok should i create a issue or u will do it or do i directly make change do a pr?
