### ISSUE TITLE
Create Ravenclaw Page

### ISSUE THREAD

**Issue by arnav1776** [arnav1776/Hogwarts#28]
Create a new page about Rowena Ravenclaw and Ravenclaw House which opens when you click this button. 
![image](https://user-images.githubusercontent.com/64467851/136378534-4d664004-80e8-4b05-9a55-df49e8a153f1.png)
 
Don't forget to link the page to this button. also create a separate folder for this by naming it Ravenclaw & use a theme of blue, white & black colors to make this page.

**Comment by arnav1776** [comment]
@MariamChowdhury the template has been updated check it here [template](https://github.com/arnav1776/Hogwarts/tree/master/house_page_template) , feel free to customize it but keep the basic structure same.

**Comment by arnav1776** [comment]
@MariamChowdhury checking in for a status update on your work.

**Comment by arnav1776** [comment]
@MariamChowdhury No problem, take your time.

**Comment by appledora** [comment]
@arnav1776 hi, is there anything similar that I could be assigned?
