### ISSUE TITLE
Improve Responsive UI 

### ISSUE THREAD

**Issue by sinc0115** [arnav1776/Hogwarts#48]
**Is your feature request related to a problem? Please describe.**
The quiz looks great on smaller screens (phones, laptops) but the UI becomes very stretched on larger screens (like a 4k monitor). 

**Describe the solution you'd like**
I would like to use media queries and set a max-width and margins for larger screens. 

**Describe alternatives you've considered**
I have also considered simply adding left/right margins to help make the horizontal stretching look intentional... but the UI would still be very stretched. 

**Additional context**
![Screenshot 2021-10-10 140136](https://user-images.githubusercontent.com/46421126/136707834-52659a8c-8a63-4350-b598-2769dd6aee3e.png)

**Comment by arnav1776** [comment]
Sure you can work on this.

**Comment by PreetiBaskey** [comment]
hey @sinc0115 , here is some of my work , if you like it, kindly accept my PR and assign me the issue.
Thank You.

Login Page :https://user-images.githubusercontent.com/38905783/136708186-37a023b7-b9d5-4ca3-a035-6def7e42fc40.jpg

Landing Page : https://user-images.githubusercontent.com/38905783/136708207-081c8742-67fe-4561-ade2-e6f94a3a0213.jpg

Location Access Page : https://user-images.githubusercontent.com/38905783/136708215-30b3b0f3-3348-476b-bc84-41c8fcaeeae3.jpg

Check In Page : https://user-images.githubusercontent.com/38905783/136708223-ec570b1e-644f-43b0-ad4a-67e5a8274805.jpg

Success Page : https://user-images.githubusercontent.com/38905783/136708234-a5e93053-1b67-46f3-b010-578c4f7b6baf.jpg

**Comment by arnav1776** [comment]
@PreetiBaskey this issue has already been assigned and how is the PR that you have created relevant to the project please don't spam unnecessarily.
