### ISSUE TITLE
Design changes in House pages

### ISSUE THREAD

**Issue by arnav1776** [arnav1776/Hogwarts#53]
Make the Gryffindor and Slytherin pages similar to the Hufflepuff one, 

1. Add a logo 
2. create a back button
3. center the traits 
4. Align Slytherin image 
5. Remove the home & play quiz buttons
6. Change the background to a solid background instead of the image background.

![image](https://user-images.githubusercontent.com/64467851/136783990-c14d1eae-61f8-482a-ad73-25141ddce268.png)
![image](https://user-images.githubusercontent.com/64467851/136784067-179c680c-e4e1-4b3c-8ae8-62e37ecfff49.png)
![image](https://user-images.githubusercontent.com/64467851/136784173-e76408a1-b504-4208-86be-378be85372b6.png)
![image](https://user-images.githubusercontent.com/64467851/136784232-775627f6-f5d2-44f9-85c7-56590fb59c59.png)

**Comment by arnav1776** [comment]
@appledora would you like to work on this?

**Comment by appledora** [comment]
Yeah, sure if it's available :D

**Comment by appledora** [comment]
@arnav1776 should I create separate PR for Gryffindor and Slytherin ?

**Comment by appledora** [comment]
> @appledora Would you like to work on the Ravenclaw page? It's the only one left which hasn't been updated.

Sure. I will be happy to :D

**Comment by appledora** [comment]
@arnav1776 do take a look :D
