### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by arnav1776** [arnav1776/Hogwarts#6]
Change the background color from plain blue so that it can look more attractive.

**Comment by SujalSamai** [comment]
Hey!! arnav, I'm a big potterhead. thanks for making this repo, can I work on this issue?

**Comment by MonuKumar1** [comment]
Can you please assign this to me? I would really love to contribute to this project.

**Comment by arnav1776** [comment]
I'm assigning this issue to @SujalSamai as he asked first, @MonuKumar1 if  you want  can work on giving these names(Gryffindor, Slytherin, Hufflepuff & Ravenclaw)  a button look.
![image](https://user-images.githubusercontent.com/64467851/136238205-d30acbd4-9780-4094-a6ce-766af150de69.png)
