### ISSUE TITLE
Unnecessary heading in the house logo section

### ISSUE THREAD

**Issue by utkarsh1311** [arnav1776/Hogwarts#67]
**Is your feature request related to a problem? Please describe.**

I think that the heading attached to each house symbol that links to their pages is redundant and that the UI of the section will look better without the heading.

**Describe the solution you'd like**

Remove the heading of each house and make the logo act as the link to it's respective page.

**Additional context**
I would like to work on this.

**Comment by arnav1776** [comment]
Okay, I'm assigning it to you @utkarsh1311
