### ISSUE TITLE
Inconsistent background shadow for the house logos.

### ISSUE THREAD

**Issue by utkarsh1311** [arnav1776/Hogwarts#68]
**Is your feature request related to a problem? Please describe.**
The background shadow added to each house logo is inconsistent in look and looks unfinished.

**Describe the solution you'd like**
Add a similar style of shadow to each house logo. We can use the house logo dominant color to decide the shadow colors for them.

**Additional context**
I would like to work on this issue.

**Comment by arnav1776** [comment]
Assigned it to you @utkarsh1311

**Comment by utkarsh1311** [comment]
I had the same thing on my mind. I will add it surely.
