### ISSUE TITLE
Update Home Page

### ISSUE THREAD

**Issue by arnav1776** [arnav1776/Hogwarts#71]
**Is your feature request related to a problem? Please describe.**
Add more information in the Home section.

**Describe the solution you'd like**
Update this section by making it more informative and center align the House lines, also add a design to make it look more attractive.

**Additional context**
![image](https://user-images.githubusercontent.com/64467851/137594918-20d77810-b42d-4417-9624-7ca27fb6b6e8.png)

**Comment by Rahulkumar2002** [comment]
I will do it can you give some example or something

**Comment by Rahulkumar2002** [comment]
> @Rahulkumar2002 I couldn't find any great examples on the internet, what I wnat you to do is:
> - Add 2-3 lines more about Hogwarts, which you can find [here](https://harrypotter.fandom.com/wiki/Hogwarts_School_of_Witchcraft_and_Wizardry).
> - Add a light background to make the text more readable, you can use the Hogwarts castle as a background but increase the transperancy and change the font-color to black, something like [this](https://www.google.com/search?q=Hogwarts%20home%20page&tbm=isch&tbs=rimg:CVCXyNRO1dCiYf9LLJP_1aBqZsgIGCgIIABAA&client=ms-android-xiaomi-rev1&prmd=binxv&hl=en&sa=X&ved=0CBQQuIIBahcKEwjIjdPeus_zAhUAAAAAHQAAAAAQJQ&biw=393&bih=719#imgrc=R0WyomBFPxartM&imgdii=UJfI1E7V0KIHNM).
> - Create a border around this section.

Ok I will try assign it to me
