### ISSUE TITLE
Improved Home Background

### ISSUE THREAD

**Issue by Rahulkumar2002** [arnav1776/Hogwarts#74]
![Screenshot (141)](https://user-images.githubusercontent.com/88898222/137612312-aa6bf12b-99fd-44bc-9e7f-923c7db700c3.png)

>@arnav1776 , I tried to checkout for some more backgrounds , I liked this one do you want to merge it ? It looks good on screen.

**Comment by arnav1776** [comment]
@Rahulkumar2002 I think it would look better if you increase the background transparency, and could try bolding the text.

**Comment by Rahulkumar2002** [comment]
> @Rahulkumar2002 I think it would look better if you increase the background transparency, and could try bolding the text.

Checkout this one:
![Screenshot (142)](https://user-images.githubusercontent.com/88898222/137615147-62b857c6-a9db-46a1-81c8-71ec4b82e6fe.png)

**Comment by Rahulkumar2002** [comment]
And can you don't make pull request before this one which was for same issue a spam it will help me with hacktoberfest

> @Rahulkumar2002 Yaa looks good now👍

**Comment by arnav1776** [comment]
@Rahulkumar2002 Improving on your work isn't spam, they both will be counted as valid PRs.
